server:
  port: 8081
spring:
  application:
    name: sky-server1
  cloud:
    nacos:
      discovery:
        server-addr: 'localhost:8848'
    stream:
      rocketmq:
        binder:
          name-server: 'localhost:9876'
        bindings:
          orderly-msg:
            producer:
              group: orderly-group
              sync: true # 消息同步发送

          transaction-msg:
            producer:
              group: transaction-group
              transactional: true # 是否是事务消息

      bindings:
        normal-msg:
          destination: normal-topic
          content-type: application/json
          group: normal-group

        orderly-msg:
          destination: orderly-topic
          content-type: application/json
          group: orderly-group

        transaction-msg:
          destination: transaction-topic
          content-type: application/json
          group: transaction-group

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  protocol:
    name: dubbo
    port: -1 # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
  scan:
    base-packages: org.sky.service # dubbo 服务扫描基准包
  cloud:
    # 用于服务消费方订阅服务提供方的应用名称的列表，若需订阅多应用，使用 "," 分割
    subscribed-services: sky-server2

logging:
  level:
    root: DEBUG
